export const noticiasMock = [
  {
    id: '1',
    categoria: 'Alunos destaques',
    titulo: 'Alunos destaques do trimestre',
    descricao: 'Confira os alunos que receberam destaque por seu comportamento e compromisso.',
    conteudo: 'Os alunos destaques do trimestre foram reconhecidos pela comunidade escolar por seu compromisso, participação e dedicação ao longo das atividades.',
    imagem: 'https://placehold.co/900x420',
    autor: 'Equipe EEPSAS',
    dataPublicacao: '20 de setembro de 2026',
  },
  {
    id: '2',
    categoria: 'Eventos',
    titulo: 'Trote do terceirão',
    descricao: 'Um momento de integração e celebração entre os estudantes.',
    conteudo: 'O trote do terceirão reuniu os estudantes em uma manhã de integração, criatividade e boas lembranças para a turma.',
    imagem: 'https://placehold.co/360x180',
    autor: 'Equipe EEPSAS',
    dataPublicacao: '18 de setembro de 2026',
  },
  {
    id: '3',
    categoria: 'Eventos',
    titulo: 'Conscientizações educacionais',
    descricao: 'A escola promove ações para fortalecer o cuidado e a convivência.',
    conteudo: 'As ações de conscientização educacional envolveram estudantes e professores em conversas, atividades e práticas de cuidado coletivo.',
    imagem: 'https://placehold.co/360x180',
    autor: 'Equipe pedagógica',
    dataPublicacao: '15 de setembro de 2026',
  },
  {
    id: '4',
    categoria: 'Eventos',
    titulo: 'Louva Jaguaraçu 2026',
    descricao: 'A comunidade escolar se prepara para mais uma edição do evento.',
    conteudo: 'O Louva Jaguaraçu 2026 contará com apresentações e momentos de encontro para celebrar os talentos da nossa comunidade.',
    imagem: 'https://placehold.co/360x180',
    autor: 'Equipe EEPSAS',
    dataPublicacao: '12 de setembro de 2026',
  },
  {
    id: '5',
    categoria: 'Conquista',
    titulo: 'Eventos da escola',
    descricao: 'Veja os principais eventos e momentos vividos pela nossa comunidade escolar.',
    conteudo: 'A escola compartilha os principais eventos e momentos vividos pela comunidade escolar durante este período letivo.',
    imagem: 'https://placehold.co/500x650',
    autor: 'Equipe EEPSAS',
    dataPublicacao: '10 de setembro de 2026',
  },
];

export const getNoticiaById = (id) => noticiasMock.find((noticia) => noticia.id === id);
