export const DEFAULT_NOTICIAS = [
  {
    id: '1',
    destaque: true,
    categoria: 'Destaque',
    titulo: 'Notícia Destaque',
    descricao: 'Confira as principais novidades e destaques do portal EEPSAS. As informações atualizadas serão sincronizadas do servidor.',
    conteudo: 'Conteúdo da notícia em destaque.',
    miniatura: 'https://placehold.co/900x420/e7ebf2/172951?text=Not%C3%ADcia+Destaque',
    imagem: 'https://placehold.co/900x420/e7ebf2/172951?text=Not%C3%ADcia+Destaque',
    autor: 'Equipe EEPSAS',
    dataPublicacao: 'Hoje',
  },
  {
    id: '2',
    categoria: 'Eventos',
    titulo: 'Notícia 1',
    descricao: 'Informações sobre os principais eventos e atividades escolares.',
    conteudo: 'Conteúdo da notícia 1.',
    miniatura: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+1',
    imagem: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+1',
    autor: 'Equipe EEPSAS',
    dataPublicacao: 'Hoje',
  },
  {
    id: '3',
    categoria: 'Eventos',
    titulo: 'Notícia 2',
    descricao: 'Ações educacionais e novidades pedagógicas da comunidade.',
    conteudo: 'Conteúdo da notícia 2.',
    miniatura: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+2',
    imagem: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+2',
    autor: 'Equipe pedagógica',
    dataPublicacao: 'Hoje',
  },
  {
    id: '4',
    categoria: 'Eventos',
    titulo: 'Notícia 3',
    descricao: 'Projetos e conquistas dos estudantes da escola.',
    conteudo: 'Conteúdo da notícia 3.',
    miniatura: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+3',
    imagem: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+3',
    autor: 'Equipe EEPSAS',
    dataPublicacao: 'Hoje',
  },
  {
    id: '5',
    categoria: 'Outros',
    titulo: 'Notícia 4',
    descricao: 'Fique por dentro de comunicados e avisos gerais para a comunidade.',
    conteudo: 'Conteúdo da notícia 4.',
    miniatura: 'https://placehold.co/360x480/e7ebf2/172951?text=Not%C3%ADcia+4',
    imagem: 'https://placehold.co/360x480/e7ebf2/172951?text=Not%C3%ADcia+4',
    autor: 'Equipe EEPSAS',
    dataPublicacao: 'Hoje',
  },
  {
    id: '6',
    categoria: 'Outros',
    titulo: 'Notícia 5',
    descricao: 'Acompanhe todas as atualizações do portal escolar EEPSAS.',
    conteudo: 'Conteúdo da notícia 5.',
    miniatura: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+5',
    imagem: 'https://placehold.co/360x220/e7ebf2/172951?text=Not%C3%ADcia+5',
    autor: 'Equipe EEPSAS',
    dataPublicacao: 'Hoje',
  },
];

export const noticiasMock = DEFAULT_NOTICIAS;

export const getNoticiaById = (id) => noticiasMock.find((noticia) => noticia.id === id);
